from pydantic import BaseModel, Field, field_validator
from typing import Any, Optional


class ChatRequest(BaseModel):
    query: str = Field(
        ...,
        min_length=3,
        max_length=500,
        description="Natural language question about Maharashtra engineering colleges.",
        examples=["Best colleges in Nagpur for Computer Engineering under 80 percentile"],
    )

    @field_validator("query")
    @classmethod
    def strip_and_validate(cls, v: str) -> str:
        stripped = v.strip()
        if not stripped:
            raise ValueError("Query must not be blank.")
        return stripped


class ChatResponse(BaseModel):
    query: str = Field(..., description="The original user query.")
    sql_generated: str = Field(..., description="SQL query generated by the AI.")
    answer: str = Field(..., description="Human-readable answer based on DB results.")
    row_count: int = Field(..., description="Number of rows returned from the database.")


class ErrorResponse(BaseModel):
    error: str
    detail: Optional[str] = None


